apiVersion: apps/v1
kind: Deployment
metadata:
  name: scala-publisher
spec:
  selector:
    matchLabels:
      app: scala-publisher
  replicas: 0
  template:
    metadata:
      labels:
        app: scala-publisher
    spec:
      containers:
      - name: scala-publisher
        image: elmanhasa/scala-publisher:latest
