apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-payment-events
spec:
  selector:
    matchLabels:
      app: rabbitmq-payment-events
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq-payment-events
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-payment-events
spec:
  selector:
    app: rabbitmq-payment-events
  ports:
    - name: mq-management
      port: 15672
      nodePort: 30020
    - name: mq-consumer
      port: 5672
      nodePort: 30030
  type: NodePort
